{
 "title": "PoolMaster Overview",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "pH & Orp",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "pH" }
   ],
   "targets": [
    {
     "alias": "pH",
     "measurement": "PoolMaster",
     "query": "from(bucket: \"HomeAssistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"PoolMaster\" and r._field == \"pH\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _value: float(v: r._value) / 100.0} ))",
     "select": [
      [
       { "params": [ "pH" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Orp",
     "measurement": "PoolMaster",
     "query": "from(bucket: \"HomeAssistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"PoolMaster\" and r._field == \"Orp\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n",
     "select": [
      [
       { "params": [ "Orp" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Chl Pump",
     "measurement": "PoolMaster",
     "query": "from(bucket: \"HomeAssistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"PoolMaster\" and r._field == \"ChlPumpState\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n",
     "select": [
      [
       { "params": [ "ChlPumpState" ], "type": "field" },
       { "params": [ "*7.5" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "pH Pump",
     "measurement": "PoolMaster",
     "query": "from(bucket: \"HomeAssistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"PoolMaster\" and r._field == \"pHPumpState\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "pHPumpState" ], "type": "field" },
       { "params": [ "*7.5" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Water temp.",
     "measurement": "PoolMaster",
     "query": "from(bucket: \"HomeAssistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"PoolMaster\" and r._field == \"Tmp\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _value: float(v: r._value) / 100.0} ))\r\n",
     "select": [
      [
       { "params": [ "Tmp" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Outside temp.",
     "measurement": "PoolMaster",
     "query": "from(bucket: \"HomeAssistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"PoolMaster\" and r._field == \"TmpExt\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _value: float(v: r._value) / 100.0} ))\r\n",
     "select": [
      [
       { "params": [ "Tmp" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water Temperature and Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Pressure (bar)" }
   ],
   "targets": [
    {
     "alias": "Pressure",
     "measurement": "PoolMaster",
     "query": "from(bucket: \"HomeAssistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"PoolMaster\" and r._field == \"PSI\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _value: float(v: r._value) / 100.0} ))",
     "select": [
      [
       { "params": [ "PSI" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Temperature",
     "measurement": "PoolMaster",
     "query": "from(bucket: \"HomeAssistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"PoolMaster\" and r._field == \"Tmp\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _value: float(v: r._value) / 100.0} ))",
     "select": [
      [
       { "params": [ "Tmp" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Filtration",
     "measurement": "PoolMaster",
     "query": "from(bucket: \"HomeAssistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"FiltState\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "FiltState" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Orp",
     "measurement": "PoolMaster",
     "query": "from(bucket: \"HomeAssistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PoolMaster\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Orp\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "Orp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mode",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "PoolMaster",
     "query": "from(bucket: \"HomeAssistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PoolMaster\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"AutoMode\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "AutoMode" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Filtration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 2, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "PoolMaster",
     "query": "from(bucket: \"HomeAssistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PoolMaster\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"FiltState\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "FiltState" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Up time chl pump",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "PoolMaster",
     "query": "from(bucket: \"HomeAssistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ChlUpT\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n  |> map(fn: (r) => ({ _value: r._value / 60.0 }))\r\n  |> cumulativeSum(columns: [\"_value\"])",
     "select": [
      [
       { "params": [ "ChlUpT" ], "type": "field" },
       { "params": [ "/60" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tank level",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "ChlTank",
     "measurement": "PoolMaster",
     "query": "from(bucket: \"HomeAssistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PoolMaster\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ChlF\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "ChlF" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "AcidTank",
     "measurement": "PoolMaster",
     "query": "from(bucket: \"HomeAssistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PoolMaster\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"AcidF\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "AcidF" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "pH",
     "measurement": "PoolMaster",
     "query": "from(bucket: \"HomeAssistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"PoolMaster\" and r._field == \"pH\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _value: float(v: r._value) / 100.0} ))\r\n  ",
     "select": [
      [
       { "params": [ "pH" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heat",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "PoolMaster",
     "query": "from(bucket: \"HomeAssistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PoolMaster\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"WaterHeat\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "WaterHeat" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Up time pH pump ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "PoolMaster",
     "query": "from(bucket: \"HomeAssistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PoolMaster\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PhUpT\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n  |> map(fn: (r) => ({ _value: r._value / 60.0 }))\r\n  |> cumulativeSum(columns: [\"_value\"])",
     "select": [
      [
       { "params": [ "PhUpT" ], "type": "field" },
       { "params": [ "/60" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}